<template>
    <div class="auth-page p-3">
        <div class="container p-5">
            <h2 class="color-wh fs-22 fw-600">Forget Password</h2>
            <p class="color-sv fs-13">Enter your email to reset password</p>
            <form class="mt-4" @submit.prevent="forgetSend()">
                <div class="form-group">
                    <label for="email" class="fs-12 fw-600 color-wh">Email</label>
                    <input type="text" placeholder="Email Address" class="form-control rg-input" name="username" v-model="email"/>
                </div>
                <button class="btn btn-primary pl-4 pr-4 mb-4 mt-4 auth-btn d-flex text-center justify-content-center position-relative">
                    <p class="mb-0 fs-12">Send Email</p>
                    <svg v-if="load" xmlns="http://www.w3.org/2000/svg" class="position-absolute ml-auto" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block; shape-rendering: auto;right:14px;" width="30px" height="20px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                        <path fill="none" stroke="#ffffff" stroke-width="8" stroke-dasharray="42.76482137044271 42.76482137044271" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-linecap="round" style="transform:scale(0.8);transform-origin:50px 50px">
                        <animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0;256.58892822265625"></animate>
                        </path>
                        <!-- [ldio] generated by https://loading.io/ -->
                    </svg>
                </button>
            </form>
        </div>
    </div>
</template>

<script>
import { mapActions } from "vuex"


export default ({
    data() {
       return {
           size: window.innerWidth,
           email: '',
           load: false,
           emailReg: new RegExp('.*@.*.\.\.*')
       }  
    },

    methods: {
        ...mapActions([
            'forget'
        ]),

        forgetSend()
        {
            if(this.email.length > 0 && this.emailReg.test(this.email)) {
                this.load = true;
                this.forget({email: this.email}).then((res) => {
                    this.email = '',
                    this.$notify({ type: res.success, text: res.payload  })
                    this.load = false;
                })
            } else {
                this.$notify({type: 'error',text:'Enter a valid email address to send reset email'})
            }
        }
    },

    mounted() {
        window.addEventListener('resize',() => {
            this.size = window.innerWidth
        })
    }
})
</script>

