<template>
    <div class="login auth-page p-3">
        <div class="container p-5">
            <h2 class="color-wh fs-22 fw-600">Let's sign you in</h2>
            <p class="color-sv fs-13">Welcome back we missed you hommie</p>
            <div class="access mt-3">
                <a href="/users/socialite/facebook" class="w-100">
                    <button class="fb-btn social-btn d-flex align-items-center justify-content-center w-100"> 
                        <i class="ri-facebook-circle-fill fs-17 pl-2"></i>
                        <span class="d-block pl-4">Continue with Facebook</span>
                    </button>
                </a>
                <a href="/users/socialite/google" class="w-100">
                    <button class="go-btn social-btn d-flex align-items-center justify-content-center mt-2 w-100">
                        <i class="ri-google-fill fs-17 pl-2"></i>
                        <span class="d-block pl-4">Continue with Google</span>
                    </button>
                </a>
            </div>
            <form class="login mt-4" @submit.prevent="loginUser()">
                <div class="form-group">
                    <label for="email" class="fs-12 fw-600 color-wh">Email Address</label>
                    <input type="text" placeholder="Email Address" class="form-control rg-input" name="email" v-model="payload.email"/>
                    <p class="error" v-if="error.email">{{ error.email }}</p>
                </div>
                <div class="form-group">
                    <label for="email" class="fs-12 fw-600 color-wh">Password</label>
                    <input type="text" placeholder="Password" class="form-control rg-input" name="password" v-model="payload.password"/>
                    <p class="error" v-if="error.password">{{ error.password }}</p>
                </div>
                <div class="form-group d-flex align-items-center lower-part">
                    <div class="d-flex align-items-center">
                        <label class="switch mb-0">
                            <input type="checkbox" class="d-none" checked v-model="payload.remember">
                            <span class="slider round d-flex justify-content-center align-items-center"></span>
                        </label>
                        <label for="email" class="fs-12  color-wh m-0 pl-2">Remember Me</label>
                    </div>
                    <div class="ml-auto">
                        <router-link :to="{name:'forget'}">
                            <p class="mb-0 fs-12  mb-1">Forget Password?</p>
                        </router-link>
                        <router-link :to="{name:'register'}">
                            <p class="mb-0 fs-12 ">Create a new member?</p>
                        </router-link>
                    </div>
                </div>
                <button class="btn btn-primary pl-4 pr-4 mb-4 mt-4 auth-btn d-flex justify-content-center" @click="load = true">
                    <p class="mb-0 fs-12 mr-3">Login</p>
                    <svg v-if="load" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block; shape-rendering: auto;" width="30px" height="20px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                        <path fill="none" stroke="#ffffff" stroke-width="8" stroke-dasharray="42.76482137044271 42.76482137044271" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-linecap="round" style="transform:scale(0.8);transform-origin:50px 50px">
                        <animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0;256.58892822265625"></animate>
                        </path>
                        <!-- [ldio] generated by https://loading.io/ -->
                    </svg>
                </button>
                <p class="error" v-if="error.login">{{ error.login }}</p>

            </form>
        </div>
    </div>
</template>

<script>
import { mapActions } from "vuex"


export default ({
    data() {
        return {
            load: false,
            payload: {},
            error: {}
        }
    },

    methods: {
        ...mapActions([
            'login'
        ]),

        loginUser()
        {
            this.login(this.payload).then((res) => {
                this.load = false;
                if(res.success) this.$router.push({name: 'discover'});
            })
        }
    }
})
</script>
